### ISSUE TITLE
failed to reproduce the accuracy of WRN-28-10 on Cifar-10

### ISSUE THREAD

**Issue by xmoanvaf** [meliketoy/Pytorch-wide-resnet#5]
unable to reproduce the acc on cifar-10 use wrn-28-10. The gap between the reported acc and th actual acc is huge while all hyper parameters are exactly the same.

**Comment by bmsookim** [comment]
The problem could be with the 'F.dropout' function in the issue below!

Unfortunately I currently do not have any access to GPUs this semester :(

Will attend to the issue after June!

**Comment by zhuyiche** [comment]
Hi, i have checked the issues on F.dropout and altered the 'F.dropout' related codes according to https://github.com/xternalz/WideResNet-pytorch/blob/master/wideresnet.py. 
It terms out this is not the major problem. Seems to me there exists some implementation errors in the model. I have able to reproduce the result using xternalz git repo.

**Comment by xmoanvaf** [comment]
Hi, i have checked the issues on F.dropout and altered the 'F.dropout' related codes according to https://github.com/xternalz/WideResNet-pytorch/blob/master/wideresnet.py.
It terms out this is not the major problem. Seems to me there exist some implementation errors in the model. I have able to reproduce the result using xternalz git repo.
